### ISSUE TITLE
[BUG] cut pages are not lined up

### ISSUE THREAD

**Issue by hoonv** [CAU-OSS-2019/team-project-team9#66]
**Describe the bug**
cut pages are not lined up

**To Reproduce**
cutting more than 4 components 

**Expected behavior**
I hope the cut pages are lined up. in grid system

**Screenshots**
![image](https://user-images.githubusercontent.com/46335714/59856321-a2b86a00-93b1-11e9-8e93-023efeeee750.png)

**Chrome version**
 - [e.g. 67]

**Additional context**

**Comment by hoonv** [comment]
I think vuetify is useful.

**Comment by jhaemin** [comment]
Actually it's not a grid system and the boxes are aligned well since their size is mutable based on the inner content's height.
Also Vuetify is just a framework that helps developers use stable material user interface with ease. And it's a bad idea to adopt those things for an unique, custom software like webuffet as well as your software.
Anyway, thanks for your suggestion.
